{% set name = "conda-mirror" %}
{% set version = "0.8.2" %}

{% set url_name = name.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ url_name[0] }}/{{ url_name }}/{{ url_name }}-{{ version }}.tar.gz
  sha256: 80d09cfa2481574d2420bd4ed4913b926c4a2dd65ba8ac41cf98555ee695d92c

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - conda-mirror = conda_mirror.conda_mirror:cli

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - requests
    - pyyaml

test:
  imports:
    - conda_mirror

  commands:
    - conda-mirror --help

about:
  home: https://github.com/regro/conda-mirror
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'mirror an upstream conda channel to a local directory'

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - scopatz
    - xhochy
    
