{% set name = "conda-mirror" %}
{% set version = "0.9.0" %}

{% set url_name = name.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ url_name[0] }}/{{ url_name }}/{{ url_name }}-{{ version }}.tar.gz
  sha256: 32500b6ecabd22beffb4a62f208da261afc39b431c88f265adbd06f1805a32d3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - conda-mirror = conda_mirror.conda_mirror:cli
    - conda-diff-tar = conda_mirror.diff_tar:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - requests
    - pyyaml
    - tqdm

test:
  imports:
    - conda_mirror

  commands:
    - conda-mirror --help
    - conda-diff-tar --help

about:
  home: https://github.com/conda-incubator/conda-mirror
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'mirror an upstream conda channel to a local directory'

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - scopatz
    - xhochy
    
