{% set name = "conda-mirror" %}
{% set version = "0.10.0" %}

{% set url_name = name.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ url_name[0] }}/{{ url_name }}/{{ url_name }}-{{ version }}.tar.gz
  sha256: 99c7cfa912cff190c5051c7c2100740dbf8c74614f8f9e8431d4d5b01816100f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - conda-mirror = conda_mirror.conda_mirror:cli
    - conda-diff-tar = conda_mirror.diff_tar:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - pyyaml
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - conda_mirror

  commands:
    - conda-mirror --help
    - conda-diff-tar --help

about:
  home: https://github.com/conda-incubator/conda-mirror
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: mirror an upstream conda channel to a local directory

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - scopatz
    - xhochy
