context:
  name: conda-mirror
  version: '0.11.0'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/conda-incubator/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8eaf852a76408770af713483d57d141a9a7211887d6accc0a581220faaca52e3

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: win
        then:
          - cargo install --no-track --locked --root %PREFIX% --path .
          - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
        else:
          - export "OPENSSL_DIR=$PREFIX"
          - cargo install --no-track --locked --root $PREFIX --path .
          - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - pkg-config
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl

tests:
  - script:
      - conda-mirror --help

about:
  homepage: https://github.com/conda-incubator/conda-mirror
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Mirror conda channels

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - scopatz
    - xhochy
    - pavelzw
    - delsner
