travis:
  secure:
    BINSTAR_TOKEN: eq8BnLlnqbbURKSwYPUQshJJGTj0XldPzVQU6LGd33DdCBrRSGarLKmNaL0tZ+xtfVCbRyZ12YcpMaAHLxU9OG6LXuT3UjhpVGtJMFDuwDjcyDjmsoD3jmCR0lMqO6T2MlUg8FQCtO22fFAGWejR0PSdXqMJCBYz6ZMMD7LgzDjvC9nEvXM0GlON9ViMU8ExGaCgX6ccGM+2lTchh/8phqqH6XpHzoOjvflT/mZQ2ZEqKqibApdfekKkB+8YLMD14JkXjFQc15p/a53GhD8XDfFm/lkokaMxpa60o7eXMKu25dc/9TkBy3FSBCDQkRuATBMRfqvOOtXzBMATPKmQzgoAX/EgYJ3y7qfyWSnXWPTuktqrhkgNv/p0pYbAZ6YJDCKoKmjJooQlNjAB8veye9nczuJlo3n5nHDvp+Wd29mfvflHrbMsizsPdGImOiIb3wdLXKETHUKJbu25lXAV7BwfpQNKlp88s9omfzmwXdSUuJNkzm+M2qqL2UHbcor1vW16wLvCihwwO7ErOx+IOaWg0QV9eoWNpxa3voqQB3cqz/q3IHz/LybbqkL3VwDL3/RMsLoHif1yM5JxpF62S4AjByXSW69d78lRI6AXXjNyKEdhfOV0wU5ak4fhXXJzMQLStgJg4TarB+hdNDVjvkoV8vmIyzRZt4lkJHmvPGU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
