appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: L0kKpROqQSaYMPuqZW4tkVN1COg3WpWC9gQeIUsFOEOjBNY/AOUxOKxLJBTHHKGOYjoBcF4LBbM+rOL+l5JR2bFH0MlV3d7q0/zgOvuvAZV7RfSvWfye28h5bHVYqITYUAMwkquT4DX7Yx1R1KVsV+j31n1evvJsrHTWoEZzGyiWD8iBOidqE+WBBPk7M7oOD37uZNDx+icDtfMT6e3FHthcEqBdpufJfn1UoeYHkbiEhsr5fMuXhZg6Y4KVDImaFDrq4ICW8CccvOH0nrzzlhKwpNVpKOo77JkGyxjaNkmxt/GTwArMnMCjmyFkOIszvX27VlZDx/eSRQwGHOigMwG9AuN0GoJqSj9WqBDtAnnxDcl5XonKa2mkLzrrZTvLTNyiMuVBY7GU0rRJD9VB/rjZzTxwoiXetnETyjSggatMko+hn09BJSGKnoOuTrASxEp9EgPT1Vk3Mslmxu5XvgIfh2xEN/WdWcmdW5AvQ5RFDOD78F4I+rwtKJy0mqdS/Q64JEj6SnsNjj2z1eRYA1U1ZSFvcay10ojrBcSYhto7sAwaSYKNUquVJldOmP5E4NFh+HOJ3X9ZcywzUK8A+p5m4BUVs7JWXLDFyTefyALGTsm+8RVzrHV0xxJv3h7Z0ULVehzqGDf3RiavyO7u2dX1dVdCGJ8Gx+aEQdU0Rdc=}
provider:
  win: azure
conda_forge_output_validation: true
